# This template contains steps to build CxPlat for a single kernel mode
# configuration.

parameters:
  arch: ''
  config: 'Debug,Release'

jobs:
- job: build_winkernel_${{ parameters.arch }}
  displayName: ${{ parameters.arch }}
  pool:
    vmImage: windows-latest
  steps:
  - checkout: self
    submodules: recursive
    path: cxplat

  - task: PowerShell@2
    displayName: Prepare Build Machine
    inputs:
      pwsh: true
      filePath: scripts/prepare-machine.ps1
      arguments: -Configuration Build

  - task: NuGetCommand@2
    displayName: Nuget Restore
    inputs:
      restoreSolution: cxplat.kernel.sln

  - task: VSBuild@1
    displayName: Build Source Code (Debug)
    condition: contains('${{ parameters.config }}', 'Debug')
    inputs:
      solution: cxplat.kernel.sln
      platform: ${{ parameters.arch }}
      configuration: debug
      msbuildArgs: /p:CXPLAT_VER_SUFFIX=-official /p:CXPLAT_VER_BUILD_ID=$(Build.BuildId)

  - task: VSBuild@1
    displayName: Build Source Code (Release)
    condition: contains('${{ parameters.config }}', 'Release')
    inputs:
      solution: cxplat.kernel.sln
      platform: ${{ parameters.arch }}
      configuration: release
      msbuildArgs: /p:CXPLAT_VER_SUFFIX=-official /p:CXPLAT_VER_BUILD_ID=$(Build.BuildId)

  - template: ./upload-artifacts.yml
