#
# Continuous Integration (CI)
# This pipeline builds and validates CxPlat for all configurations.
#

trigger:
  batch: true
  branches:
    include:
    - main
    - release/*
    - feature/*
pr:
- main
- release/*
- feature/*

name: 0.$(Date:yyyy).$(Date:MM).$(DayOfMonth).$(Rev:rr).0

resources:
  containers:
  - container: raspbian
    image:  wpilib/raspbian-cross-ubuntu:10-18.04

stages:

#
# Builds
#

- stage: build_winkernel
  displayName: Build Windows Drivers
  dependsOn: []
  jobs:
  - template: ./templates/build-config-winkernel.yml
    parameters:
      arch: x64
  - template: ./templates/build-config-winkernel.yml
    parameters:
      arch: x86
  - template: ./templates/build-config-winkernel.yml
    parameters:
      arch: arm
  - template: ./templates/build-config-winkernel.yml
    parameters:
      arch: arm64

- stage: build_windows
  displayName: Build Windows
  dependsOn: []
  jobs:
  # Officially supported configurations.
  - template: ./templates/build-config-user.yml
    parameters:
      image: windows-latest
      platform: windows
      arch: x86
      tls: schannel
  - template: ./templates/build-config-user.yml
    parameters:
      image: windows-latest
      platform: windows
      arch: x64
      tls: schannel
  - template: ./templates/build-config-user.yml
    parameters:
      image: windows-latest
      platform: windows
      arch: arm
      tls: schannel
  - template: ./templates/build-config-user.yml
    parameters:
      image: windows-latest
      platform: windows
      arch: arm64
      tls: schannel
  # Other configurations.
  - template: ./templates/build-config-user.yml
    parameters:
      image: windows-latest
      platform: windows
      arch: x64
      tls: stub
  - template: ./templates/build-config-user.yml
    parameters:
      image: windows-latest
      platform: windows
      arch: x64
      tls: mitls
  - template: ./templates/build-config-user.yml
    parameters:
      image: windows-latest
      platform: uwp
      arch: x64
      tls: schannel
      extraBuildArgs: -DisableTools -DisableTest
  - template: ./templates/build-config-user.yml
    parameters:
      image: windows-latest
      platform: windows
      arch: x64
      tls: openssl

- stage: build_linux
  displayName: Build Linux
  dependsOn: []
  jobs:
  # Officially supported configurations.
  - template: ./templates/build-config-user.yml
    parameters:
      image: ubuntu-latest
      platform: linux
      arch: x64
      tls: openssl
  # Other configurations.
  - template: ./templates/build-config-user.yml
    parameters:
      image: ubuntu-latest
      platform: linux
      arch: x64
      tls: stub
      extraBuildArgs: -SanitizeAddress
  - template: ./templates/build-config-user.yml
    parameters:
      image: ubuntu-latest
      platform: linux
      arch: x64
      tls: openssl
      extraBuildArgs: -Clang
      skipArtifacts: true
      extraName: 'clang'
  - template: ./templates/build-config-user.yml
    parameters:
      image: ubuntu-latest
      container: raspbian
      platform: linux
      arch: arm
      tls: openssl
      extraBuildArgs: -DisableLogs -Generator Ninja -ToolchainFile cmake/toolchains/arm-pi-gnueabihf.toolchain.cmake
